name = "a0b_stm32g474_gpio"
description = "A0B: STM32G474 GPIO"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["a0b", "embedded"]

project-files = ["gnat/a0b_stm32g474_gpio.gpr"]

[configuration]
generate_ada = false
generate_c = false
generate_gpr = true

[[depends-on]]
a0b_stm32g4_gpio = "*"
a0b_stm32g474 = "*"

[[actions]]
type = "test"
directory = "selftest"
command = ["alr", "build"]
